### ISSUE TITLE
support minio for mongo

### ISSUE THREAD

**Issue by olexiyb** [percona/everest#164]
I see only Amazon S3 at this moment, is it possible to add support of minio

**Comment by dbazhenov** [comment]
Hi, @olexiyb 

Thank you for creating the Issue

Just wanted to say that there is a discussion on the forum on a related topic, maybe someone could use it. 
https://forums.percona.com/t/backup-to-non-aws-s3/29159/6

**Comment by recharte** [comment]
Everest supports any S3-compatible API as long as it meets 2 requirements:
1. If you use HTTPS, the TLS certificate must be signed by a trusted authority (self-signed certificates are not allowed)
2. Your S3-compatible API must support [Virtual-hosted–style requests](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#virtual-hosted-style-access) (instances using [path-style](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#path-style-access) URL access will not work)

We are planning to remove both limitations in the near future:
1. [Allowing to skip TLS certificate checks](https://perconadev.atlassian.net/browse/EVEREST-895) is already being developed and will be part of 0.10.0 which is planned to be released at the end of April
2. [Supporting path-style URL access](https://perconadev.atlassian.net/browse/EVEREST-919) is in our roadmap, no ETA on this one yet.

**Comment by recharte** [comment]
Closing this issue because because both aforementioned limitations have been addressed in [v0.10.0](https://github.com/percona/everest/releases/tag/v0.10.0) and minio is now supported.
