### ISSUE TITLE
After upgrade from v1.0.1 to v1.1.0 only everest namespace showing in UI

### ISSUE THREAD

**Issue by george-pogosyan** [percona/everest#586]
After upgrade from v1.0.1 to v1.1.0 only everest namespace showing in UI.

logs:

```
λ everestctl upgrade
✓ Upgrade Operator Lifecycle Manager
✓ Upgrade Percona Catalog
✓ Wait for Everest Operator InstallPlan
✓ Upgrade Everest API server
✓ Upgrade Everest Operator
✓ Run post-upgrade tasks
```

**Comment by recharte** [comment]
Hi @george-pogosyan, in this particular k8s cluster what was the first everest version you installed? Was it v1.0.1 or did you initially have v0.10.1 and then upgraded to v1.0.1?

**Comment by recharte** [comment]
## Issue
In `v1.0.0` we changed the way we list the managed namespaces.
While everestctl `v1.0.0`'s upgrade command had logic to upgrade from versions older than `v1.0.0`, everestctl `v1.1.0` assumed that users wouldn't be running versions older that `v1.0.0` and dropped the migration logic.

When you used everestctl `v1.1.0` to upgrade your older than `v1.0.0` version it missed the migration step needed to list the managed namespaces.

## Preemptive fix
We have added a warning in the [documentation](https://docs.percona.com/everest/upgrade_with_cli.html#upgrade) and [release notes](https://docs.percona.com/everest/release-notes/Percona-Everest-1.1.0-%282024-08-12%29.html#upgrade-instructions) explaining how avoid this.

## Fix
Now that you found yourself in this situation, you can run the following command to fix your Everest environment.
```
kubectl get deployments everest-operator-controller-manager -n everest-system -o jsonpath='{.spec.template.spec.containers[?(@.name=="manager")].env[?(@.name=="DB_NAMESPACES")].value}' | xargs -d ',' -I {} kubectl label namespaces {} app.kubernetes.io/managed-by=everest
```
