### ISSUE TITLE
Unable to delete any DB cluster after upgrading from v1.0.1 to v1.1.0

### ISSUE THREAD

**Issue by edithturn** [percona/everest#601]
I encountered an issue after upgrading Everest from version **1.0.1** to **1.1.0**. I found that I am unable to delete any database clusters created before the upgrade. The deletion process fails due to an error in missing secrets.

**Steps to Reproduce:**

1. I installed Everest v1.0.1.
2. I created PostgreSQL (PG), Percona XtraDB Cluster (PXC), and Percona Server for MongoDB (PSMDB) clusters. (For context: I created 3 clusters of each database type and enabled external access on 2 of the 3 clusters.)
4. I upgraded Everest to v1.1.0.
5. I then attempted to delete the DB clusters that were created prior to the upgrade.

**Expected Result:**
I expected the clusters to be deleted without any issues.

**Actual Result:**
The clusters were stuck in the "Deleting" state. The error message I received was: Secrets "everest-secrets-mongodb-gl8" not found.

**Note:** 

- I did not create any backups before the upgrade.

**Comment by recharte** [comment]
JIRA ticket for tracking: [EVEREST-1349](https://perconadev.atlassian.net/browse/EVEREST-1349)
